name: Docker Image Builder

on:
  workflow_call:
    inputs:
      platform:
        description: 'The platform to build the image for'
        required: true
        type: string
      push-to-docker-hub:
        description: 'Whether the image should be pushed to Docker hub'
        required: true
        type: boolean
      push-to-ghcr:
        description: 'Whether the image should be pushed to GHCR'
        required: true
        type: boolean
      path:
        description: 'The path to the Dockerfile to build'
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        description: 'The token used to access Docker hub'
        required: true
    
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          name=ngreatorex/homie-streamdeck,enable=${{ inputs.push-to-docker-hub }}
          name=ghcr.io/${{ github.actor }}/homie-streamdeck,enable=${{ inputs.push-to-ghcr }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: inputs.push-to-docker-hub
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GHCR
      uses: docker/login-action@v3
      if: inputs.push-to-ghcr
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        config-inline: |
          [worker.oci]
            max-parallelism = 2
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platform }}

