name: Docker CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]
    
jobs:

  enumerate-config-dirs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate matrix with all config sub-directories
        id: set-matrix
        run: |
          echo "matrix=$(ls -l config/ | grep '^d' | awk -F ' ' '{print $9}' | grep -v '^images$' | jq -R -s -c 'split("\n") | map(select(length > 0))') >> $GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  
  build-base-image:
    needs: enumerate-config-dirs
    uses: ./.github/workflows/build-docker-image.yml
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(vars.DOCKER_PLATFORMS) }}
    with:
      platform: ${{ matrix.platform }}
      push-to-docker-hub: ${{ github.event_name != 'pull_request' }}
      push-to-ghcr: ${{ github.event_name == 'pull_request' }}
      path: .
    secrets: inherit

  build-config-images:
    needs: 
      - enumerate-config-dirs
      - build-base-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        platform: ${{ fromJson(vars.DOCKER_PLATFORMS) }} 
        subdir: ${{ fromJson(needs.enumerate-config-dirs.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo matrix
        run: |
          echo "${{ matrix.subdir }}"
    
